### ISSUE TITLE
building on Mac OS results in a  libgdal unable to load because of libpoppler

### ISSUE THREAD

**Issue by aashish24** [conda-forge/libgdal-feedstock#22]
libgdal needs libpoppler however it is getting two version of this. It is linked against the libpoppler.66.dylib but when installed it installed with libpoppler.71.dylib and then complains about not finding the 66 version. I am not sure what is going on here. 

./pkgs/poppler-0.52.0-2/lib/libpoppler.66.dylib
./pkgs/poppler-0.52.0-2/lib/libpoppler.dylib
./pkgs/poppler-0.60.1-hb654a48_0/lib/libpoppler.71.0.0.dylib
./pkgs/poppler-0.60.1-hb654a48_0/lib/libpoppler.71.dylib
./pkgs/poppler-0.60.1-hb654a48_0/lib/libpoppler.dylib
./pkgs/poppler-0.52.0-3/lib/libpoppler.66.dylib
./pkgs/poppler-0.52.0-3/lib/libpoppler.dylib
./envs/test/lib/libpoppler.71.0.0.dylib
./envs/test/lib/libpoppler.71.dylib
./envs/test/lib/libpoppler.dylib
./envs/test2/lib/libpoppler.71.0.0.dylib
./envs/test2/lib/libpoppler.71.dylib
./envs/test2/lib/libpoppler.dylib

>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aashishchaudhary/miniconda3/envs/test2/lib/python3.6/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/Users/aashishchaudhary/miniconda3/envs/test2/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/aashishchaudhary/miniconda3/envs/test2/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/Users/aashishchaudhary/miniconda3/envs/test2/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/aashishchaudhary/miniconda3/envs/test2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/aashishchaudhary/miniconda3/envs/test2/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.66.dylib
  Referenced from: /Users/aashishchaudhary/miniconda3/envs/test2/lib/libgdal.20.dylib
  Reason: image not found
>>>

**Comment by ocefpaf** [comment]
Based on your title I am assuming you are trying to build `libgdal`. If so you will need a clean env with only 1 `poppler` installed. If that is a problem with the conda-forge built package please re-open and report how you installed uit.

**Comment by egayer** [comment]
Hi guys,
I just created a fresh clean env, then installed gdal from conda-forge channel, and only gdal. I can't import gdal because of an error also regarding libpoppler

> ImportError: dlopen(/Applications/PythonAnaconda/anaconda/envs/forge/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/libpoppler.66.dylib
  Referenced from: /Applications/PythonAnaconda/anaconda/envs/forge/lib/libgdal.20.dylib
  Reason: image not found

PS : here is what I get on conda list

> poppler                   0.61.1                        1    conda-forge

**Comment by aashish24** [comment]
@ocefpaf can we open this issue?

**Comment by ocefpaf** [comment]
> @ocefpaf can we open this issue?

First try:

```
conda create --yes --channel conda-forge --name TEST gdal
source activate TEST
python -c 'import gdal;print(dir(gdal))'
```

and report back the results if that does not work.
