### ISSUE TITLE
poppler dependency issue: OS-X build

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/libgdal-feedstock#28]
I see that in the meta.yaml, the dependency is:

    - poppler 0.61.*  # [not win]

but the libgdal I just downloaded (OS-X -- python2.7)

has this:

```
$ otool -L libgdal.20.dylib 

libgdal.20.dylib:

...
	@rpath/libpoppler.66.dylib (compatibility version 67.0.0, current version 67.0.0)
```

and, indeed, it fails when I try to use it, as it can't find libpoppler.66

How did it get built against that version in the first place???

and popper 0.61.1 seems to be the latest on conda-forge.

**Comment by ChrisBarker-NOAA** [comment]
Just to make sure it wasn't something weird with my otherwise complicated environment, I just started from scratch:

```
$ conda create -n gdal_test python=2

$ source activate gdal_test

$ conda install gdal
```
and get, among a lot of others:
`poppler:       0.61.1-1      conda-forge`

```
$ python -c "from osgeo import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/chris.barker/miniconda2/envs/gdal_test/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/chris.barker/miniconda2/envs/gdal_test/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: dlopen(/Users/chris.barker/miniconda2/envs/gdal_test/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/libpoppler.66.dylib
  Referenced from: /Users/chris.barker/miniconda2/envs/gdal_test/lib/libgdal.20.dylib
  Reason: image not found
```

**Comment by gillins** [comment]
I can confirm the same thing here on Linux. I'm a bit confused when you create a new environment you get `gdal` 2.2.2, but the latest is 2.2.3. When you try and upgrade to 2.2.3 manually, I get the following which seems really weird. @ocefpaf do you have any ideas? Maybe some versions need to be marked broken.
```
The following packages will be UPDATED:

    libgdal:  2.2.2-7      conda-forge --> 2.2.3-1      conda-forge
    openjpeg: 2.1.2-3      conda-forge --> 2.3.0-1      conda-forge
    poppler:  0.61.1-1     conda-forge --> 0.61.1-2     conda-forge

The following packages will be DOWNGRADED:

    gdal:     2.2.2-py27_1 conda-forge --> 2.0.0-py27_1            
```

**Comment by ocefpaf** [comment]
@gillins it is just our Travis-CI backlog taking too long to build the OS X packages for `2.2.3`. I was not planning on re-building `2.2.2` BTW but, later today, `2.1.3`, `2.1.4` and `2.2.3` should be good to go.

**Comment by gillins** [comment]
Thanks @ocefpaf

**Comment by ChrisBarker-NOAA** [comment]
I’m confused — is there a new poppler in the waiting list? If so, how did Linda get built against a not yet available poppler?

**Comment by ChrisBarker-NOAA** [comment]
That is — how did GDAL get built with a not yet there poppler? Darn auto-correct.

**Comment by ocefpaf** [comment]
> I’m confused — is there a new poppler in the waiting list?

No. There is a `gdal`, pinned to the new `poppler`, in the wait list. The old `gdal` was not pinned b/c there was only 1 `poppler` until defaults updated it.

> That is — how did GDAL get built with a not yet there poppler?

That is not what that message means. It means "tried to run with a new `poppler` but expected the old one."
