### ISSUE TITLE
lib netcdf dep out of sync with netCDF4 

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/libgdal-feedstock#29]
See the issue on the netCDF4 feedstock:

https://github.com/conda-forge/netcdf4-feedstock/issues/42

**Comment by ocefpaf** [comment]
Not really. See https://github.com/conda-forge/netcdf4-feedstock/issues/42

It is a conda usage "feature."

**Comment by ChrisBarker-NOAA** [comment]
Not really. See conda-forge/netcdf4-feedstock#42
<https://github.com/conda-forge/netcdf4-feedstock/issues/42>

It is a conda usage "feature."

Well, mid-feature if you ask me, maybe I’ll post on the conda repo...

But thanks, got it to work with more careful pinning.

Also:

conda install gdal netCDF4

Worked well, too.

**Comment by ocefpaf** [comment]
> Not really. See conda-forge/netcdf4-feedstock#42

Not sure what you mean by that. The pinning is in sync, we only have options there.

> Also:
> conda install gdal netCDF4
> Worked well, too.

The only way to guarantee the version of `gdal` you want is by specifying it. Conda can return another combination if the situation is slightly different.

**Comment by ChrisBarker-NOAA** [comment]
sure -- but I don't want a particular version -- I want "as recent as possible of both netcdf and gdal".

note that this went to heck even though I didn't specify a version for either. 

Ideally, you'd get the same thing whether you installed gdal first, or netcdf first, or both at once, if you didn't specify a version for either.

But in this case, there are multiple builds of netcdf4 often same version with different requirements -- so it's no wonder that conda can't find an "optimum" combination.

At any rate, this is a conda issue (if an issue at all), not a conda-forge one.

Though perhaps this would be all more clear if the netcdf4 versioning matched the libnetcdf that it's linked to -- like gdal and libgdal.

**Comment by ocefpaf** [comment]
> sure -- but I don't want a particular version -- I want "as recent as possible of both netcdf and gdal".

I mentioned that b/c you said: `Ouch! Though they do appear to work (at least both import into python) but I need gdal >= 2.0!` in https://github.com/conda-forge/netcdf4-feedstock/issues/42

> Though perhaps this would be all more clear if the netcdf4 versioning matched the libnetcdf that it's linked to -- like gdal and libgdal.

`gdal` and `libgdal` are the same package, only different outputs that, I personally, don't like but we had to do to follow `defaults`. `netCDF4-python` and `netcdf-c` (named `libnetcdf` here also to match `defaults`) are not the same package and that would not make sense. People do need different combinations of those two for different applications.
