### ISSUE TITLE
SQLite pinned to 3.13.*

### ISSUE THREAD

**Issue by snorfalorpagus** [conda-forge/libgdal-feedstock#30]
SQLite is pinned to version `3.13.*` - is there a reason for this?

https://github.com/conda-forge/libgdal-feedstock/blob/2e0661663519cd99387e6c26736e0cfb33594569/recipe/meta.yaml#L53

I'm unable to use GDAL with GPKG without the fix in more recent SQLite from  https://github.com/conda-forge/sqlite-feedstock/pull/20.

**Comment by ocefpaf** [comment]
The re-pinning is pending https://github.com/conda-forge/libspatialite-feedstock/pull/24

**Comment by kmuehlbauer** [comment]
BTW, @ocefpaf Can we do anything to speed up travis? It becomes more and more annoying to have a backlog of almost 2 days. 😢

**Comment by ocefpaf** [comment]
> BTW, @ocefpaf Can we do anything to speed up travis? It becomes more and more annoying to have a backlog of almost 2 days. 😢 

I'll try to use the end of the year recess to write to NumFOCUS and see if we can start gathering funds to pay them. Besides that, no. The backlog usually gets processed over the weekend though.

**Comment by kmuehlbauer** [comment]
I thought so. Thanks for your efforts!

**Comment by ocefpaf** [comment]
Fixed in #31
