### ISSUE TITLE
Error with international encodings

### ISSUE THREAD

**Issue by snorfalorpagus** [conda-forge/libgdal-feedstock#32]
I'm having some problems with non-utf encodings with the conda-forge build of GDAL. The script below triggers the issue: it creates a new shapefile with GB18030 encoding (simplified Chinese), adds a single feature and writes it to disk.

```
from osgeo import ogr

driver = ogr.GetDriverByName("ESRI Shapefile")
ds = driver.CreateDataSource("test.shp")
lyr = ds.CreateLayer("test", options=["ENCODING=GB18030"])

field_defn = ogr.FieldDefn("myfield", ogr.OFTString)
lyr.CreateField(field_defn)

lyr_defn = lyr.GetLayerDefn()
feature = ogr.Feature(lyr_defn)

feature.SetField("myfield", "\u5f90\u6c47\u533a")

lyr.CreateFeature(feature)

lyr = None
ds = None
```

When running the above script on Windows using python+gdal from conda-forge, I get the following error.

```
ERROR 1: Failed to create field name 'myfield': cannot convert to GB18030
ERROR 1: Invalid field name: 'myfield'
```

When running the script on Fedora Linux with python+gdal from yum (i.e. not using conda), the script runs correctly without outputting any message, and the shapefile is created correctly as demonstrated below.

```
[root@6914dd166ccc ~]# ogrinfo -al test.shp
INFO: Open of `test.shp'
      using driver `ESRI Shapefile' successful.

Layer name: test
Metadata:
  DBF_DATE_LAST_UPDATE=2018-01-07
Geometry: Line String
Feature Count: 1
Extent: (0.000000, 0.000000) - (0.000000, 0.000000)
Layer SRS WKT:
(unknown)
myfield: String (80.0)
OGRFeature(test):0
  myfield (String) = 徐汇区区
```

I suspect this is an issue with either the libiconv binary from conda, or the way GDAL has been linked to libiconv. In the macOS build log I see the following:

```
checking for iconv... yes
checking for working iconv... no
```

Downstream issue: https://github.com/Toblerity/Fiona/issues/526

**Comment by snorfalorpagus** [comment]
The following warning is seen in the appveyor build log:

```
[00:04:05] cpl_recode_iconv.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
```

**Comment by snorfalorpagus** [comment]
Another data point: the GDAL binary I have installed via OSGeo4W is linked to libiconv correctly (I can see it's loaded with Process Monitor) and the test script above works as expected.

**Comment by snorfalorpagus** [comment]
Adding the following lines to `bld.bat` fixes this on Windows.

```
    LIBICONV_INCLUDE="-I%LIBRARY_INC% -DICONV_CONST= " ^
    LIBICONV_LIBRARY="%LIBRARY_LIB%\iconv.lib" ^
```

I suspect the `-DICONV_CONST= ` doesn't belong here, but I'm not sure where it should go.

Still need a fix for macOS...

**Comment by gillins** [comment]
> Adding the following lines to bld.bat fixes this on Windows.

Thanks. Do you want to send us a PR with this fix?

**Comment by ocefpaf** [comment]
@gillins and @snorfalorpagus I am testing this in https://github.com/conda-forge/libgdal-feedstock/pull/33/commits/04bad915a98d3d3c8dbea49bb0e1ceae0630deae fingers crossed!

**Comment by snorfalorpagus** [comment]
I can't figure out what the problem is on macOS. It might be conflicting with the system install of libiconv which is a different version, but I really don't know.

**Comment by ocefpaf** [comment]
> I can't figure out what the problem is on macOS. It might be conflicting with the system install of libiconv which is a different version, but I really don't know.

That is probably it but I don't own a macOS to investigate and/or test possible solutions.

**Comment by gillins** [comment]
Often GDAL's `configure` doesn't properly honour the paths that you specify.... I'll have a look when I get a moment. 

ps Would be good to add a test for `iconv` presence similar to https://github.com/conda-forge/libgdal-feedstock/issues/32#issue-286576863.

**Comment by gillins** [comment]
Does specifying `--with-libiconv-prefix` help?

**Comment by ocefpaf** [comment]
> Does specifying `--with-libiconv-prefix` help?

Testing that in https://github.com/conda-forge/libgdal-feedstock/pull/33/commits/38d88d0d240bff7792672eb348a92440bb488f55

> Would be good to add a test for `iconv` presence similar to https://github.com/conda-forge/libgdal-feedstock/issues/32#issue-286576863.

Not sure that code caught the issue @snorfalorpagus documented on Windows. Everything passed when I added that as a test in https://github.com/conda-forge/gdal-feedstock/pull/196

(Or maybe I missed something and created a bad test?)

**Comment by ocefpaf** [comment]
@snorfalorpagus I think we fixed this but never got back here. Please let us know if you are still experiencing this issue.

PS: we are archiving `libgdal` and new issue should go to https://github.com/conda-forge/gdal-feedstock/issues/new
