### ISSUE TITLE
"libgdal.so.20: undefined symbol" error when importing geopandas

### ISSUE THREAD

**Issue by samfranklin** [conda-forge/libgdal-feedstock#40]
Hi there. I'm getting a geopandas import error after installation via conda.

My set up:
Platform: `linux-64` which is `Ubuntu 16.04.3 LTS` via the Windows Subsystem for Linux
conda version: `4.5.1`
anaconda3 directory: `/home/sam/anaconda3/`

I created a fresh conda environment with `conda create --name geopy python=3.6`
I installed geopandas with `conda install -c conda-forge geopandas`
I get a `libgdal.so.20:` error on `import geopandas `

```
>>> import geopandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/anaconda3/envs/geopy/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/home/sam/anaconda3/envs/geopy/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/home/sam/anaconda3/envs/geopy/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/sam/anaconda3/envs/geopy/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /home/sam/anaconda3/envs/geopy/lib/python3.6/site-packages/fiona/../../../libgdal.so.20: undefined symbol: _ZN11xercesc_3_211InputSource11setEncodingEPKDs
```

After a bit of googling...I tried a few options (kind of randomly):
`conda config --add channels conda-forge`
`conda install libkml`
`conda install gdal` > this downgraded by python version from 3.6.5 to 3.6.4 (not sure if that's significant)
I tried doing installing in the root conda, i.e. not in an environment. No difference.

Any ideas or pointers would be greatly appreciated, thanks in advance.

**Comment by ocefpaf** [comment]
Looks like a typical https://conda-forge.org/docs/conda-forge_gotchas.html

Please try a fresh env with conda-forge on top of `defaults` in your `.condarc`.

This should work,

```shell
conda create --name TEST python=3.6 geopandas
conda activate TEST
python -c "import geopandas; print(geopandas.__version__)"
```
