### ISSUE TITLE
libhdf5_cpp.so missing

### ISSUE THREAD

**Issue by sgillies** [conda-forge/libgdal-feedstock#53]
On Read the Docs I'm seeing the following error when looking into why Rasterio autodoc'ing is failing:

```
WARNING: autodoc: failed to import module 'rasterio'; the following exception was raised:
libhdf5_cpp.so.102: cannot open shared object file: No such file or directory
```

Forgive me if I should have filed this at hdf5-feedstock, but I'm not sure which package is at fault.

This issue blocks Rasterio 1.0 from having API docs when it is released. Count me in for any help needed to close it!

**Comment by ocefpaf** [comment]
Can you point me to the configuration? We are building packages with `hdf5 1.10.2` now and the `rasterio` stack is working, but my guess is that something is forcing an `hdf5` downgrade there. For example, this works:

```shell
conda create --name TEST python=3.6 rasterio
conda activate TEST
python -c 'import rasterio; print(rasterio.__version__)'
```

**Comment by sgillies** [comment]
@ocefpaf https://github.com/mapbox/rasterio/blob/master/environment.yml. It was working as of 1.0b1, but I lost track of when conda installs started to fail.

**Comment by ocefpaf** [comment]
Thanks. I'm looking into it. I guess I know where the problem lies... Hold on.

**Comment by sgillies** [comment]
@ocefpaf thanks!
